apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-service-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-github-username/argo-microservice-sample.git
    targetRevision: main
    path: lab/my-service
  destination:
    server: https://kubernetes.default.svc
    namespace: lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
