apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
  namespace: lab
  labels:
    app: my-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: my-service
        image: yourname/my-service:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
